TooManyRacesRequired  = Class.new(RuntimeError)
TooManyPlayers        = Class.new(RuntimeError)
PlayersHaveBeenChosen = Class.new(RuntimeError)
PlayerDoNotHaveName   = Class.new(RuntimeError)
IdenticalPlayersNames = Class.new(RuntimeError)
RaceNotAssign         = Class.new(RuntimeError)
RaceNameDoNotExist    = Class.new(RuntimeError)
PlayerNotFound        = Class.new(RuntimeError)
